import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useQueryClient } from "react-query";
import styles from "../styles/Home.module.css";
import { SSR_PREFETCHING_KEY } from "../src/utils/constants";
import { getContacts } from "../src/utils/contacts";

export default function Home() {
  const queryClient = useQueryClient();

  async function onLinkHover() {
    await queryClient.prefetchQuery(SSR_PREFETCHING_KEY, getContacts, {
      staleTime: 3000,
    });
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Prefetching data with next.js and React Query</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <div>Prefetching data with</div>
          <div>
            <a href="https://nextjs.org">Next.js</a> and{" "}
            <a href="https://react-query.tanstack.com/">React Query</a>
          </div>
        </h1>

        <p className={styles.description}>@matldupont</p>

        <div className={styles.grid}>
          <Link href="/1-client-side-rendering">
            <a className={styles.card}>
              <h2>Client-side Rendering &rarr;</h2>
              <p>A traditional, client-only Single-Page Application.</p>
            </a>
          </Link>

          <Link href="/2-csr-react-query">
            <a className={styles.card} onMouseOver={onLinkHover}>
              <h2>CSR with React Query &rarr;</h2>
              <p>Prefetch on hover to preload react-query cache</p>
            </a>
          </Link>

          <Link href="/3-server-side-rendering">
            <a className={styles.card}>
              <h2>Server-side Rendering &rarr;</h2>
              <p>
                Completely rendered from the server and hydrated on the client.
              </p>
            </a>
          </Link>

          <Link href="/4-ssr-prefetching">
            <a className={styles.card}>
              <h2>SSR Prefetching with React Query &rarr;</h2>
              <p>Prefetch on the server to preload react-query cache</p>
            </a>
          </Link>

          <Link href="/5-csr-prefetching">
            <a className={styles.card} onMouseOver={onLinkHover}>
              <h2>CSR Prefetching with React Query &rarr;</h2>
              <p>Prefetch on hover to preload react-query cache</p>
            </a>
          </Link>

          <a
            href="https://github.com/matldupont/next-react-query"
            className={styles.card}
          >
            <h2>matldupont/next-react-query &rarr;</h2>
            <p>The code repository for this demo application</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
